# k8s/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Override the namespace for all resources in this overlay
namespace: arcascian-tools

# Prefix all resource names (e.g. bugbot -> arcascian-bugbot)
namePrefix: arcascian-

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
